name: cd

on:
  push:
    branches: ["dev", "qa", "main"]

jobs:
  deploy-DEV:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - run: echo "Deployed to DEV"

  deploy-QA:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - run: echo "Deployed to QA"

  deploy-PROD:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - run: echo "Deployed to Prod"
