name: cd

on:
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deployed to DEV"

  QA:
    runs-on: ubuntu-latest

    needs: DEV
    steps:
      - name: Deploy
        run: echo "Deployed to QA"

  PROD:
    runs-on: ubuntu-latest

    needs: QA
    steps:
      - name: Deploy
        run: echo "Deployed to Prod"
